package org.opengamestudio

val BUDG_INITIAL_SUM = 20000f
val BUDG_RESTDAY_SUM = 5000f
val BUDG_RESULT_DATE_T = "%DATE%"
val BUDG_RESULT_LEFT_T = "Осталось Р/д: %VALUE%"
val BUDG_RESULT_OVERRUN_T = "Перерасход: %VALUE%"
val BUDG_RESULT_WEEKDAY_T = "Будни: %SPENT% / %BALANCE% %PERCENT%"
val BUDG_RESULT_WEEKEND_T = "Выходные: %SPENT% / %BALANCE% %PERCENT%"
val BUDG_WEEKDAY_MON = 1
val BUDG_WEEKDAY_TUE = 2
val BUDG_WEEKDAY_WED = 3
val BUDG_WEEKDAY_THU = 4
val BUDG_WEEKDAY_FRI = 5
val BUDG_WEEKDAY_SAT = 6
val BUDG_WEEKDAY_SUN = 7
val BUDG_WORKDAY_SUM = 4000f
