#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

cd $SDIR/../ver-android/app/src/main/kotlin/org/opengamestudio
tmux new-window -n and

cd $SDIR/../ver-ios/src
#tmux new-window -n ios

cd $SDIR/../sdk-ios
#tmux new-window -n sdk-ios

cd $SDIR/../ver-mac-x64/src
tmux new-window -n mac
