#!/bin/bash -e
SDIR=$(cd "$(dirname "$0")" ; pwd -P)

BUILD_DIR=$SDIR/../sdk-ios/gb/build/XCFrameworks/release

$SDIR/gen-kd

# Build and archive KMP code into a framework for iOS
cd $SDIR/../sdk-ios
./gradlew assembleGbReleaseXCFramework
cd $BUILD_DIR
zip -r gb.xcframework.zip gb.xcframework

# Generate iOS project
cd $SDIR/../ver-ios/app
xcodegen
