name: GitBudget
packages:
    gb:
        path: local/gb
options:
    bundleIdPrefix: org.opengamestudio
targets:
    gitbudget:
        type: application
        platform: iOS
        deploymentTarget: "15.0"
        dependencies:
           - package: gb
        sources:
            - path: "../src"
        settings:
            base:
                DEVELOPMENT_TEAM: S3NW8F382K
                INFOPLIST_FILE: Info.plist
